name: Deployment Ali-DEV
on:
  push:
    branches: [main]
  pull_request:
jobs:
  vercel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Create env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_SANITY_STUDIO_READ_TOKEN: ${{ secrets.SANITY_STUDIO_READ_TOKEN }}
          envkey_SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          envkey_SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          envkey_SANITY_GRAPHQL_API_VERSION: ${{ secrets.SANITY_GRAPHQL_API_VERSION }}
          envkey_SANITY_GROQ_API_VERSION: ${{ secrets.SANITY_GROQ_API_VERSION }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false
      - name: Build
        run: npm run build
      - name: Start Deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment-preview
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: Preview
      - name: Deploy to Preview
        id: vercel-action-preview
        if: github.ref != 'refs/heads/main'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to Production
        uses: amondnet/vercel-action@v25
        id: vercel-action-production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          github-comment: false
          vercel-args: "--prod"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Deployment Status
        uses: bobheadxi/deployments@v0.4.3
        if: github.ref != 'refs/heads/main'
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment-preview.outputs.deployment_id }}
          env_url: ${{ steps.vercel-action-preview.outputs.preview-url }}
